// /// Flutter icons MyFlutterApp
// /// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
// /// This font was generated by FlutterIcon.com, which is derived from Fontello.
// ///
// /// To use this font, place it in your fonts/ directory and include the
// /// following in your pubspec.yaml
// ///
// /// flutter:
// ///   fonts:
// ///    - family:  MyFlutterApp
// ///      fonts:
// ///       - asset: fonts/MyFlutterApp.ttf
// ///
// ///
// /// * Typicons, (c) Stephen Hutchings 2012
// ///         Author:    Stephen Hutchings
// ///         License:   SIL (http://scripts.sil.org/OFL)
// ///         Homepage:  http://typicons.com/
// /// * Entypo, Copyright (C) 2012 by Daniel Bruce
// ///         Author:    Daniel Bruce
// ///         License:   SIL (http://scripts.sil.org/OFL)
// ///         Homepage:  http://www.entypo.com
// /// * Linearicons Free, Copyright (C) Linearicons.com
// ///         Author:    Perxis
// ///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
// ///         Homepage:  https://linearicons.com
// ///
// library;
// import 'package:flutter/widgets.dart';
//
// class CustomIcon {
//   CustomIcon._();
//
//   static const _kFontFam = 'MyFlutterApp';
//   static const String? _kFontPkg = null;
//
//
//   static const IconData ok_outline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData check = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sad = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData download = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);}